import { MigrationInterface, QueryRunner } from "typeorm";

export class  $npmConfigName1701014348219 implements MigrationInterface {
    name = ' $npmConfigName1701014348219'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "Users" ("userId" number GENERATED BY DEFAULT AS IDENTITY, "name" varchar2(255) NOT NULL, "phone" varchar2(20), "sex" varchar2(10), "email" varchar2(100) NOT NULL, "password" varchar2(255) NOT NULL, "avatar" varchar2(500), "address" varchar2(500), "role" varchar2(10) DEFAULT 'customer' NOT NULL, "createdAt" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT "UQ_3c3ab3f49a87e6ddb607f3c4945" UNIQUE ("email"), CONSTRAINT "PK_a06d29e81a4b836dddfd684ab87" PRIMARY KEY ("userId"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "Users"`);
    }

}
