import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateAllTables1701076594375 implements MigrationInterface {
  name = ' CreateAllTables1701076594375';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "details" ("sizeName" varchar2(10) NOT NULL, "quantity" number NOT NULL, "productId" number NOT NULL, CONSTRAINT "PK_56aa81ad368d072a2a2f93dd715" PRIMARY KEY ("sizeName", "quantity", "productId"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "detail_product_fk" ON "details" ("productId")`,
    );
    await queryRunner.query(
      `CREATE TABLE "images" ("productId" number NOT NULL, "imageLink" varchar2(500) NOT NULL, CONSTRAINT "PK_809d901ccb1e11f07dce14b2b5a" PRIMARY KEY ("productId", "imageLink"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "categories" ("categoryId" number GENERATED BY DEFAULT AS IDENTITY, "name" varchar2(500) NOT NULL, "description" clob, CONSTRAINT "PK_c9594c262e6781893a1068d91be" PRIMARY KEY ("categoryId"))`,
    );
    await queryRunner.query(
      `CREATE UNIQUE INDEX "name" ON "categories" ("name")`,
    );
    await queryRunner.query(
      `CREATE TABLE "collections" ("collectionId" number GENERATED BY DEFAULT AS IDENTITY, "name" varchar2(500), "description" clob, CONSTRAINT "PK_439ce999fe0130001a2015c3eb1" PRIMARY KEY ("collectionId"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "usersratingproducts" ("userId" number NOT NULL, "productId" number NOT NULL, "time" date DEFAULT CURRENT_TIMESTAMP, "comment" varchar2(255), "star" number, CONSTRAINT "PK_9934e7d2f97283d9bc82d2aae55" PRIMARY KEY ("userId", "productId"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "userratingproducts_product_fk" ON "usersratingproducts" ("productId")`,
    );
    await queryRunner.query(
      `CREATE TABLE "users" ("userId" number GENERATED BY DEFAULT AS IDENTITY, "name" varchar2(255), "phone" varchar2(20), "sex" varchar2(10), "email" varchar2(100) NOT NULL, "password" varchar2(255), "avatar" varchar2(1200), "address" varchar2(255), "role" varchar2(10) DEFAULT 'customer', "createdAt" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT "PK_8bf09ba754322ab9c22a215c919" PRIMARY KEY ("userId"))`,
    );
    await queryRunner.query(`CREATE UNIQUE INDEX "email" ON "users" ("email")`);
    await queryRunner.query(
      `CREATE TABLE "usershaveorders" ("orderId" number NOT NULL, "userId" number, CONSTRAINT "PK_2e59b6ce199355cc675e85e656f" PRIMARY KEY ("orderId"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "userhaveorders_user_fk" ON "usershaveorders" ("userId")`,
    );
    await queryRunner.query(
      `CREATE TABLE "orders" ("orderId" number GENERATED BY DEFAULT AS IDENTITY, "status" varchar2(20) DEFAULT 'Pending', "phone" varchar2(20), "cost" float(12), "note" varchar2(255), "address" varchar2(255), "paid" number DEFAULT 0 NOT NULL, "paymentMethod" varchar2(50) DEFAULT 'Cash', "paymentDate" date, "orderTime" date DEFAULT CURRENT_TIMESTAMP NOT NULL, "deliveryTime" date, CONSTRAINT "PK_41ba27842ac1a2c24817ca59eaa" PRIMARY KEY ("orderId"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "productsinorders" ("productId" number NOT NULL, "orderId" number NOT NULL, "size" varchar2(10) NOT NULL, "quantity" number, CONSTRAINT "PK_5d1e869db84d41ea23c00ba9582" PRIMARY KEY ("productId", "orderId", "size"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "productinorder_order_fk" ON "productsinorders" ("orderId")`,
    );
    await queryRunner.query(
      `CREATE TABLE "sizes" ("sizeName" varchar2(10) NOT NULL, "quantity" number NOT NULL, "productId" number NOT NULL, "price" float(12) NOT NULL, CONSTRAINT "PK_f7b1de4c2ab78393f3366dfd235" PRIMARY KEY ("sizeName", "quantity", "productId", "price"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "size_product_fk" ON "sizes" ("productId")`,
    );
    await queryRunner.query(
      `CREATE TABLE "products" ("productId" number GENERATED BY DEFAULT AS IDENTITY, "name" varchar2(500), "description" clob, "createdAt" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "deleted" number DEFAULT 0, CONSTRAINT "PK_7b3b507508cd0f86a5b2e923459" PRIMARY KEY ("productId"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "carts" ("cartId" number GENERATED BY DEFAULT AS IDENTITY, "productId" number, "userId" number NOT NULL, "size" varchar2(10), "quantity" number DEFAULT '1', "time" date DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "PK_75eb343efb7459aad5dd7f8045c" PRIMARY KEY ("cartId"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "cart_product_fk" ON "carts" ("productId")`,
    );
    await queryRunner.query(
      `CREATE INDEX "cart_user_fk" ON "carts" ("userId")`,
    );
    await queryRunner.query(
      `CREATE TABLE "productsincategories" ("categoryId" number NOT NULL, "productId" number NOT NULL, CONSTRAINT "PK_5706c7e77fd5731f2b80a3cf051" PRIMARY KEY ("categoryId", "productId"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_26c89cc22f51b964c756d62d12" ON "productsincategories" ("categoryId")`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_eca7ccafeeeb37e8561ac3cc26" ON "productsincategories" ("productId")`,
    );
    await queryRunner.query(
      `CREATE TABLE "productsincollections" ("collectionId" number NOT NULL, "productId" number NOT NULL, CONSTRAINT "PK_3b9a3efed9f646f7066ce227b59" PRIMARY KEY ("collectionId", "productId"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_29fa0cddb5cd85a0922c1b0eb4" ON "productsincollections" ("collectionId")`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_be741ea722453a55e0b6209f86" ON "productsincollections" ("productId")`,
    );
    await queryRunner.query(
      `ALTER TABLE "details" ADD CONSTRAINT "FK_d038e5da5a06a4b0ef85919de41" FOREIGN KEY ("productId") REFERENCES "products" ("productId") ON DELETE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "images" ADD CONSTRAINT "FK_7af50639264735c79e918af6089" FOREIGN KEY ("productId") REFERENCES "products" ("productId") ON DELETE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "usersratingproducts" ADD CONSTRAINT "FK_2aecea9a86cf5152df829cf485e" FOREIGN KEY ("productId") REFERENCES "products" ("productId") ON DELETE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "usersratingproducts" ADD CONSTRAINT "FK_74f966ced334e60174270988f28" FOREIGN KEY ("userId") REFERENCES "users" ("userId") ON DELETE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "usershaveorders" ADD CONSTRAINT "FK_2e59b6ce199355cc675e85e656f" FOREIGN KEY ("orderId") REFERENCES "orders" ("orderId") ON DELETE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "usershaveorders" ADD CONSTRAINT "FK_dcaf5c995b8eabbb31b1af5bd72" FOREIGN KEY ("userId") REFERENCES "users" ("userId") ON DELETE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "productsinorders" ADD CONSTRAINT "FK_6718b23eee209a97711a3364d25" FOREIGN KEY ("orderId") REFERENCES "orders" ("orderId") ON DELETE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "productsinorders" ADD CONSTRAINT "FK_c96d7595a96344a110946a57ff2" FOREIGN KEY ("productId") REFERENCES "products" ("productId") ON DELETE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "sizes" ADD CONSTRAINT "FK_a88acd8214bb21b8da633b8c9ce" FOREIGN KEY ("productId") REFERENCES "products" ("productId") ON DELETE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "carts" ADD CONSTRAINT "FK_9c77aaa5bc26f66159661ffd808" FOREIGN KEY ("productId") REFERENCES "products" ("productId") ON DELETE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "carts" ADD CONSTRAINT "FK_69828a178f152f157dcf2f70a89" FOREIGN KEY ("userId") REFERENCES "users" ("userId") ON DELETE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "productsincategories" ADD CONSTRAINT "FK_26c89cc22f51b964c756d62d125" FOREIGN KEY ("categoryId") REFERENCES "categories" ("categoryId") ON DELETE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "productsincategories" ADD CONSTRAINT "FK_eca7ccafeeeb37e8561ac3cc26e" FOREIGN KEY ("productId") REFERENCES "products" ("productId")`,
    );
    await queryRunner.query(
      `ALTER TABLE "productsincollections" ADD CONSTRAINT "FK_29fa0cddb5cd85a0922c1b0eb46" FOREIGN KEY ("collectionId") REFERENCES "collections" ("collectionId") ON DELETE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "productsincollections" ADD CONSTRAINT "FK_be741ea722453a55e0b6209f86b" FOREIGN KEY ("productId") REFERENCES "products" ("productId")`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "productsincollections" DROP CONSTRAINT "FK_be741ea722453a55e0b6209f86b"`,
    );
    await queryRunner.query(
      `ALTER TABLE "productsincollections" DROP CONSTRAINT "FK_29fa0cddb5cd85a0922c1b0eb46"`,
    );
    await queryRunner.query(
      `ALTER TABLE "productsincategories" DROP CONSTRAINT "FK_eca7ccafeeeb37e8561ac3cc26e"`,
    );
    await queryRunner.query(
      `ALTER TABLE "productsincategories" DROP CONSTRAINT "FK_26c89cc22f51b964c756d62d125"`,
    );
    await queryRunner.query(
      `ALTER TABLE "carts" DROP CONSTRAINT "FK_69828a178f152f157dcf2f70a89"`,
    );
    await queryRunner.query(
      `ALTER TABLE "carts" DROP CONSTRAINT "FK_9c77aaa5bc26f66159661ffd808"`,
    );
    await queryRunner.query(
      `ALTER TABLE "sizes" DROP CONSTRAINT "FK_a88acd8214bb21b8da633b8c9ce"`,
    );
    await queryRunner.query(
      `ALTER TABLE "productsinorders" DROP CONSTRAINT "FK_c96d7595a96344a110946a57ff2"`,
    );
    await queryRunner.query(
      `ALTER TABLE "productsinorders" DROP CONSTRAINT "FK_6718b23eee209a97711a3364d25"`,
    );
    await queryRunner.query(
      `ALTER TABLE "usershaveorders" DROP CONSTRAINT "FK_dcaf5c995b8eabbb31b1af5bd72"`,
    );
    await queryRunner.query(
      `ALTER TABLE "usershaveorders" DROP CONSTRAINT "FK_2e59b6ce199355cc675e85e656f"`,
    );
    await queryRunner.query(
      `ALTER TABLE "usersratingproducts" DROP CONSTRAINT "FK_74f966ced334e60174270988f28"`,
    );
    await queryRunner.query(
      `ALTER TABLE "usersratingproducts" DROP CONSTRAINT "FK_2aecea9a86cf5152df829cf485e"`,
    );
    await queryRunner.query(
      `ALTER TABLE "images" DROP CONSTRAINT "FK_7af50639264735c79e918af6089"`,
    );
    await queryRunner.query(
      `ALTER TABLE "details" DROP CONSTRAINT "FK_d038e5da5a06a4b0ef85919de41"`,
    );
    await queryRunner.query(`DROP INDEX "IDX_be741ea722453a55e0b6209f86"`);
    await queryRunner.query(`DROP INDEX "IDX_29fa0cddb5cd85a0922c1b0eb4"`);
    await queryRunner.query(`DROP TABLE "productsincollections"`);
    await queryRunner.query(`DROP INDEX "IDX_eca7ccafeeeb37e8561ac3cc26"`);
    await queryRunner.query(`DROP INDEX "IDX_26c89cc22f51b964c756d62d12"`);
    await queryRunner.query(`DROP TABLE "productsincategories"`);
    await queryRunner.query(`DROP INDEX "cart_user_fk"`);
    await queryRunner.query(`DROP INDEX "cart_product_fk"`);
    await queryRunner.query(`DROP TABLE "carts"`);
    await queryRunner.query(`DROP TABLE "products"`);
    await queryRunner.query(`DROP INDEX "size_product_fk"`);
    await queryRunner.query(`DROP TABLE "sizes"`);
    await queryRunner.query(`DROP INDEX "productinorder_order_fk"`);
    await queryRunner.query(`DROP TABLE "productsinorders"`);
    await queryRunner.query(`DROP TABLE "orders"`);
    await queryRunner.query(`DROP INDEX "userhaveorders_user_fk"`);
    await queryRunner.query(`DROP TABLE "usershaveorders"`);
    await queryRunner.query(`DROP INDEX "email"`);
    await queryRunner.query(`DROP TABLE "users"`);
    await queryRunner.query(`DROP INDEX "userratingproducts_product_fk"`);
    await queryRunner.query(`DROP TABLE "usersratingproducts"`);
    await queryRunner.query(`DROP TABLE "collections"`);
    await queryRunner.query(`DROP INDEX "name"`);
    await queryRunner.query(`DROP TABLE "categories"`);
    await queryRunner.query(`DROP TABLE "images"`);
    await queryRunner.query(`DROP INDEX "detail_product_fk"`);
    await queryRunner.query(`DROP TABLE "details"`);
  }
}
